--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class CollectibleConfig
---@overload fun(data, path):CollectibleConfig
local CollectibleConfig = class:derive("CollectibleConfig")



---Constructs an instance of CollectibleConfig.
---@param data table Raw data from a file.
---@param path string Path to the file. The file is not loaded here, and it is not used in error messages, but some classes use it for saving data. TODO: Find an alternative.
function CollectibleConfig:new(data, path)
    local u = _ConfigUtils
    self._path = path

    self.a = u.parseString(data.a, path, "a")
end



return CollectibleConfig