--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class ColorPaletteConfig
---@overload fun(data, path):ColorPaletteConfig
local ColorPaletteConfig = class:derive("ColorPaletteConfig")



---Constructs an instance of ColorPaletteConfig.
---@param data table Raw data from a file.
---@param path string Path to the file. The file is not loaded here, and it is not used in error messages, but some classes use it for saving data. TODO: Find an alternative.
function ColorPaletteConfig:new(data, path)
    local u = _ConfigUtils
    self._path = path

    self.image = u.parseImage(data.image, path, "image")
end



return ColorPaletteConfig