--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class HighscoresConfig
---@overload fun(data, path):HighscoresConfig
local HighscoresConfig = class:derive("HighscoresConfig")



---Constructs an instance of HighscoresConfig.
---@param data table Raw data from a file.
---@param path string Path to the file. The file is not loaded here, and it is not used in error messages, but some classes use it for saving data. TODO: Find an alternative.
function HighscoresConfig:new(data, path)
    local u = _ConfigUtils
    self._path = path

    self.size = u.parseInteger(data.size, path, "size")
    self.defaultScores = {}
    for i = 1, #data.defaultScores do
        self.defaultScores[i] = {}
        self.defaultScores[i].name = u.parseString(data.defaultScores[i].name, path, "defaultScores[" .. tostring(i) .. "].name")
        self.defaultScores[i].score = u.parseInteger(data.defaultScores[i].score, path, "defaultScores[" .. tostring(i) .. "].score")
        self.defaultScores[i].level = u.parseString(data.defaultScores[i].level, path, "defaultScores[" .. tostring(i) .. "].level")
    end
end



return HighscoresConfig