--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class LevelSpeedTransitionConfig
---@overload fun(data, path):LevelSpeedTransitionConfig
local LevelSpeedTransitionConfig = class:derive("LevelSpeedTransitionConfig")



---Constructs an instance of LevelSpeedTransitionConfig.
---@param data table Raw data from a file.
---@param path string Path to the file. The file is not loaded here, and it is not used in error messages, but some classes use it for saving data. TODO: Find an alternative.
function LevelSpeedTransitionConfig:new(data, path)
    local u = _ConfigUtils
    self._path = path

    self.type = u.parseString(data.type, path, "type")
    if self.type == "linear" then
        -- No fields
    elseif self.type == "bezier" then
        self.point1 = u.parseNumber(data.point1, path, "point1")
        self.point2 = u.parseNumber(data.point2, path, "point2")
    else
        error(string.format("Unknown LevelSpeedTransitionConfig type: %s (expected \"linear\" or \"bezier\")", self.type))
    end
end



return LevelSpeedTransitionConfig