--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class LevelSetConfig
---@overload fun(data, path):LevelSetConfig
local LevelSetConfig = class:derive("LevelSetConfig")



---Constructs an instance of LevelSetConfig.
---@param data table Raw data from a file.
---@param path string Path to the file. The file is not loaded here, and it is not used in error messages, but some classes use it for saving data. TODO: Find an alternative.
function LevelSetConfig:new(data, path)
    local u = _ConfigUtils
    self._path = path

    self.levelOrder = {}
    for i = 1, #data.levelOrder do
        self.levelOrder[i] = u.parseLevelSetEntry(data.levelOrder[i], path, "levelOrder[" .. tostring(i) .. "]")
    end
    self.checkpoints = {}
    for i = 1, #data.checkpoints do
        self.checkpoints[i] = u.parseInteger(data.checkpoints[i], path, "checkpoints[" .. tostring(i) .. "]")
    end
    self.startCheckpoints = {}
    for i = 1, #data.startCheckpoints do
        self.startCheckpoints[i] = u.parseInteger(data.startCheckpoints[i], path, "startCheckpoints[" .. tostring(i) .. "]")
    end
end



return LevelSetConfig