--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class LevelSetEntryConfig
---@overload fun(data, path):LevelSetEntryConfig
local LevelSetEntryConfig = class:derive("LevelSetEntryConfig")



---Constructs an instance of LevelSetEntryConfig.
---@param data table Raw data from a file.
---@param path string Path to the file. The file is not loaded here, and it is not used in error messages, but some classes use it for saving data. TODO: Find an alternative.
function LevelSetEntryConfig:new(data, path)
    local u = _ConfigUtils
    self._path = path

    self.type = u.parseString(data.type, path, "type")
    if self.type == "level" then
        self.level = u.parseInteger(data.level, path, "level")
        self.name = u.parseString(data.name, path, "name")
        self.unlockCheckpointsOnBeat = {}
        if data.unlockCheckpointsOnBeat then
            for i = 1, #data.unlockCheckpointsOnBeat do
                self.unlockCheckpointsOnBeat[i] = u.parseInteger(data.unlockCheckpointsOnBeat[i], path, "unlockCheckpointsOnBeat[" .. tostring(i) .. "]")
            end
        end
    elseif self.type == "randomizer" then
        self.pool = {}
        for i = 1, #data.pool do
            self.pool[i] = u.parseInteger(data.pool[i], path, "pool[" .. tostring(i) .. "]")
        end
        self.names = {}
        for i = 1, #data.names do
            self.names[i] = u.parseString(data.names[i], path, "names[" .. tostring(i) .. "]")
        end
        self.count = u.parseInteger(data.count, path, "count")
        self.mode = u.parseString(data.mode, path, "mode")
        self.unlockCheckpointsOnBeat = {}
        if data.unlockCheckpointsOnBeat then
            for i = 1, #data.unlockCheckpointsOnBeat do
                self.unlockCheckpointsOnBeat[i] = u.parseInteger(data.unlockCheckpointsOnBeat[i], path, "unlockCheckpointsOnBeat[" .. tostring(i) .. "]")
            end
        end
    else
        error(string.format("Unknown LevelSetEntryConfig type: %s (expected \"level\" or \"randomizer\")", self.type))
    end
end



return LevelSetEntryConfig