--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class LevelSpawnRulesConfig
---@overload fun(data, path):LevelSpawnRulesConfig
local LevelSpawnRulesConfig = class:derive("LevelSpawnRulesConfig")



---Constructs an instance of LevelSpawnRulesConfig.
---@param data table Raw data from a file.
---@param path string Path to the file. The file is not loaded here, and it is not used in error messages, but some classes use it for saving data. TODO: Find an alternative.
function LevelSpawnRulesConfig:new(data, path)
    local u = _ConfigUtils
    self._path = path

    self.type = u.parseString(data.type, path, "type")
    if self.type == "waves" then
        self.amount = u.parseInteger(data.amount, path, "amount")
    elseif self.type == "continuous" then
        -- No fields
    else
        error(string.format("Unknown LevelSpawnRulesConfig type: %s (expected \"waves\" or \"continuous\")", self.type))
    end
end



return LevelSpawnRulesConfig