--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class MapConfig
---@overload fun(data, path):MapConfig
local MapConfig = class:derive("MapConfig")



---Constructs an instance of MapConfig.
---@param data table Raw data from a file.
---@param path string Path to the file. The file is not loaded here, and it is not used in error messages, but some classes use it for saving data. TODO: Find an alternative.
function MapConfig:new(data, path)
    local u = _ConfigUtils
    self._path = path

    self.name = u.parseString(data.name, path, "name")
    self.paths = {}
    for i = 1, #data.paths do
        self.paths[i] = {}
        for j = 1, #data.paths[i] do
            self.paths[i][j] = {}
            self.paths[i][j].x = u.parseNumber(data.paths[i][j].x, path, "paths[" .. tostring(i) .. "][" .. tostring(j) .. "].x")
            self.paths[i][j].y = u.parseNumber(data.paths[i][j].y, path, "paths[" .. tostring(i) .. "][" .. tostring(j) .. "].y")
            self.paths[i][j].scale = u.parseNumberOpt(data.paths[i][j].scale, path, "paths[" .. tostring(i) .. "][" .. tostring(j) .. "].scale")
            self.paths[i][j].hidden = u.parseBooleanOpt(data.paths[i][j].hidden, path, "paths[" .. tostring(i) .. "][" .. tostring(j) .. "].hidden")
            self.paths[i][j].warp = u.parseBooleanOpt(data.paths[i][j].warp, path, "paths[" .. tostring(i) .. "][" .. tostring(j) .. "].warp")
        end
    end
    self.sprites = {}
    for i = 1, #data.sprites do
        self.sprites[i] = {}
        self.sprites[i].x = u.parseNumber(data.sprites[i].x, path, "sprites[" .. tostring(i) .. "].x")
        self.sprites[i].y = u.parseNumber(data.sprites[i].y, path, "sprites[" .. tostring(i) .. "].y")
        self.sprites[i].path = u.parseSprite(data.sprites[i].path, path, "sprites[" .. tostring(i) .. "].path")
        self.sprites[i].background = u.parseBooleanOpt(data.sprites[i].background, path, "sprites[" .. tostring(i) .. "].background")
        self.sprites[i].foreground = u.parseBooleanOpt(data.sprites[i].foreground, path, "sprites[" .. tostring(i) .. "].foreground")
    end
end



return MapConfig