--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class MusicTrackConfig
---@overload fun(data, path):MusicTrackConfig
local MusicTrackConfig = class:derive("MusicTrackConfig")



---Constructs an instance of MusicTrackConfig.
---@param data table Raw data from a file.
---@param path string Path to the file. The file is not loaded here, and it is not used in error messages, but some classes use it for saving data. TODO: Find an alternative.
function MusicTrackConfig:new(data, path)
    local u = _ConfigUtils
    self._path = path

    self.audio = u.parseSound(data.audio, path, "audio")
end



return MusicTrackConfig