--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class UI2NodeChildConfig
---@overload fun(data, path):UI2NodeChildConfig
local UI2NodeChildConfig = class:derive("UI2NodeChildConfig")



---Constructs an instance of UI2NodeChildConfig.
---@param data table Raw data from a file.
---@param path string Path to the file. The file is not loaded here, and it is not used in error messages, but some classes use it for saving data. TODO: Find an alternative.
function UI2NodeChildConfig:new(data, path)
    local u = _ConfigUtils
    self._path = path

    self.type = u.parseString(data.type, path, "type")
    if self.type == "include" then
        self.layout = u.parseString(data.layout, path, "layout")
    elseif self.type == "node" then
        self.node = u.parseUI2Node(data.node, path, "node")
    else
        error(string.format("Unknown UI2NodeChildConfig type: %s (expected \"include\" or \"node\")", self.type))
    end
end



return UI2NodeChildConfig