--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class UI2NodeConfig
---@overload fun(data, path):UI2NodeConfig
local UI2NodeConfig = class:derive("UI2NodeConfig")



---Constructs an instance of UI2NodeConfig.
---@param data table Raw data from a file.
---@param path string Path to the file. The file is not loaded here, and it is not used in error messages, but some classes use it for saving data. TODO: Find an alternative.
function UI2NodeConfig:new(data, path)
    local u = _ConfigUtils
    self._path = path

    self.widget = u.parseUI2WidgetOpt(data.widget, path, "widget")

    if data.children then
        self.children = {}
        self.children = u.parseUI2NodeChild(data.children, path, "children")
    end
    self.pos = u.parseVec2Opt(data.pos, path, "pos")
    self.scale = u.parseVec2Opt(data.scale, path, "scale")
    self.alpha = u.parseNumberOpt(data.alpha, path, "alpha")
    self.layer = u.parseStringOpt(data.layer, path, "layer")
end



return UI2NodeConfig