--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class UI2SequenceConfig
---@overload fun(data, path):UI2SequenceConfig
local UI2SequenceConfig = class:derive("UI2SequenceConfig")



---Constructs an instance of UI2SequenceConfig.
---@param data table Raw data from a file.
---@param path string Path to the file. The file is not loaded here, and it is not used in error messages, but some classes use it for saving data. TODO: Find an alternative.
function UI2SequenceConfig:new(data, path)
    local u = _ConfigUtils
    self._path = path

    self.timeline = {}
    for i = 1, #data.timeline do
        self.timeline[i] = u.parseUI2TimelineEntry(data.timeline[i], path, "timeline[" .. tostring(i) .. "]")
    end
end



return UI2SequenceConfig