--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class UI2TimelineEntryConfig
---@overload fun(data, path):UI2TimelineEntryConfig
local UI2TimelineEntryConfig = class:derive("UI2TimelineEntryConfig")



---Constructs an instance of UI2TimelineEntryConfig.
---@param data table Raw data from a file.
---@param path string Path to the file. The file is not loaded here, and it is not used in error messages, but some classes use it for saving data. TODO: Find an alternative.
function UI2TimelineEntryConfig:new(data, path)
    local u = _ConfigUtils
    self._path = path

    self.type = u.parseString(data.type, path, "type")
    if self.type == "playAnimation" then
        self.node = u.parseString(data.node, path, "node")
        self.animation = u.parseString(data.animation, path, "animation")
        self.waitUntilFinished = u.parseBooleanOpt(data.waitUntilFinished, path, "waitUntilFinished")
    elseif self.type == "executeCallback" then
        self.name = u.parseString(data.name, path, "name")
    elseif self.type == "wait" then
        self.time = u.parseNumber(data.time, path, "time")
    else
        error(string.format("Unknown UI2TimelineEntryConfig type: %s (expected \"playAnimation\", \"executeCallback\" or \"wait\")", self.type))
    end
end



return UI2TimelineEntryConfig