--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class UI2WidgetConfig
---@overload fun(data, path):UI2WidgetConfig
local UI2WidgetConfig = class:derive("UI2WidgetConfig")



---Constructs an instance of UI2WidgetConfig.
---@param data table Raw data from a file.
---@param path string Path to the file. The file is not loaded here, and it is not used in error messages, but some classes use it for saving data. TODO: Find an alternative.
function UI2WidgetConfig:new(data, path)
    local u = _ConfigUtils
    self._path = path

    self.type = u.parseString(data.type, path, "type")
    if self.type == "rectangle" then
        self.size = u.parseVec2(data.size, path, "size")
        self.color = u.parseColor(data.color, path, "color")
        self.align = u.parseVec2Opt(data.align, path, "align")
    elseif self.type == "sprite" then
        self.sprite = u.parseSprite(data.sprite, path, "sprite")
        self.align = u.parseVec2Opt(data.align, path, "align")
    elseif self.type == "spriteButton" then
        self.sprite = u.parseSprite(data.sprite, path, "sprite")
        self.shape = u.parseStringOpt(data.shape, path, "shape")

        if data.callbacks then
            self.callbacks = {}
            self.callbacks.onClick = u.parseStringOpt(data.callbacks.onClick, path, "callbacks.onClick")
        end
        self.align = u.parseVec2Opt(data.align, path, "align")
    elseif self.type == "text" then
        self.font = u.parseFont(data.font, path, "font")
        self.text = u.parseStringOpt(data.text, path, "text")
        self.color = u.parseColorOpt(data.color, path, "color")
        self.align = u.parseVec2Opt(data.align, path, "align")
    else
        error(string.format("Unknown UI2WidgetConfig type: %s (expected \"rectangle\", \"sprite\", \"spriteButton\" or \"text\")", self.type))
    end
end



return UI2WidgetConfig